### ISSUE TITLE
RuntimeError in parscit example

### ISSUE THREAD

**Issue by irmasuppes** [abhinavkashyap/sciwing#208]
I'm getting RuntimeError: size mismatch, when trying to run parscit.sh file from examples folder. 

The complete traceback:
![parscit_error](https://user-images.githubusercontent.com/51317371/97864211-87c96a00-1d08-11eb-93c5-e2a086a2a8fe.png)

**Comment by abhinavkashyap** [comment]
Hi @irmasuppes Thank you for the report. Are you running as it is from the example file that is present in the repository ?
