### ISSUE TITLE
ElmoEmbedder deprecated in AllenNLP

### ISSUE THREAD

**Issue by walter-hernandez** [abhinavkashyap/sciwing#22]
I see that this was included in the code (_modules/elmo_lstm_encoder.py_):
`@deprecated(
    reason="ElmoEmbedder will be deprecated "
    "Please use concat embedder and lstm 2 vec module to achieve the same thing. "
    "This will be removed in version 1",
    version=0.1,
)`

It is is still being called in the current version of sciwing:
`from sciwing.modules.embedders.elmo_embedder import ElmoEmbedder`

Which gives the module not found error when calling:
`ModuleNotFoundError: No module named 'allennlp.commands.elmo'`

The fix seems to be and since you were already considering in your code the deprecation of ElmoEmbedder, to maybe change these lines in _modules/embedders/bow_elmo_embedder.py_:

Line 2:
`from allennlp.commands.elmo import ElmoEmbedder`

for :
`from sciwing.modules.embedders.elmo_embedder import ElmoEmbedder`

Line 71:
`self.elmo = ElmoEmbedder(cuda_device=self.cuda_device_id)`

for:
`self.elmo = ElmoEmbedder()`

After making that correction, the following error comes up:
`RuntimeError: Error(s) in loading state_dict for RnnSeqCrfTagger:
	Missing key(s) in state_dict: "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder._char_embedding_weights", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_0.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_0.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_1.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_1.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_2.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_2.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_3.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_3.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_4.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_4.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_5.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_5.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_6.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder.char_conv_6.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder._highways._layers.0.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder._highways._layers.0.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder._highways._layers.1.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder._highways._layers.1.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder._projection.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._token_embedder._projection.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.forward_layer_0.input_linearity.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.forward_layer_0.state_linearity.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.forward_layer_0.state_linearity.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.forward_layer_0.state_projection.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.backward_layer_0.input_linearity.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.backward_layer_0.state_linearity.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.backward_layer_0.state_linearity.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.backward_layer_0.state_projection.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.forward_layer_1.input_linearity.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.forward_layer_1.state_linearity.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.forward_layer_1.state_linearity.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.forward_layer_1.state_projection.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.backward_layer_1.input_linearity.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.backward_layer_1.state_linearity.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.backward_layer_1.state_linearity.bias", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo._elmo_lstm._elmo_lstm.backward_layer_1.state_projection.weight", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo.scalar_mix_0.gamma", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo.scalar_mix_0.scalar_parameters.0", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo.scalar_mix_0.scalar_parameters.1", "rnn2seqencoder.embedder.embedder_elmo.elmo.elmo.scalar_mix_0.scalar_parameters.2". 
`

I guess the elmo_embedder.py is not generating the embedder the needed way or it was not intended to be used the way I was trying to use it to correct the issue with the deprecated module of ElmoEmbedder in AllenNLP

**Comment by walter-hernandez** [comment]
Forgot to mention, in the meantime, a solution is to use an old version of AllenNLP:
`pip install allennlp==0.9.0`

and use the compatible version of torch:
`pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by abhinavkashyap** [comment]
Hi, Thank you for the comments and the fix. The fixes should be available soon on pip. We will update you once this has been done

**Comment by abhinavkashyap** [comment]
Fixed this! Requirements are pinned for installation from pip.
